namespace TZService.Contracts.NotifyRefChangeAsync;
public class Reference
{
    public string STM18I { get; set;}
    public string STMCC { get; set;}
    public string STMM05 { get; set;}
    public string STMM06 { get; set;}
    public string STMM07 { get; set;}
    public string STMM08 { get; set;}
    public string STMM09 { get; set;}
    public string STMM10 { get; set;}
    public string STMM11 { get; set;}
    public string STMM12 { get; set;}
    public string STMM13 { get; set;}
    public string STMM14 { get; set;}
    public string STMM15 { get; set;}
    public string STMM16 { get; set;}
    public string STMM17 { get; set;}
    public string STMM18 { get; set;}
    public string STMM19 { get; set;}
    public string STMM20 { get; set;}
    public string STMM21 { get; set;}
    public string STMM22 { get; set;}
    public string STMM23 { get; set;}
    public string STMM24 { get; set;}
    public string STMM25 { get; set;}
    public string STMM26 { get; set;}
    public string STMM27 { get; set;}
    public string STMM29 { get; set;}
    public string STMM30 { get; set;}
    public string STMM31 { get; set;}
    public string STMM32 { get; set;}
    public string STMM33 { get; set;}
    public string STMM34 { get; set;}
    public string STMM35 { get; set;}
    public string STMM36 { get; set;}
    public string STMM37 { get; set;}
    public string STMM38 { get; set;}
    public string STMM39 { get; set;}
    public string STMM40 { get; set;}
    public string STMM41 { get; set;}
    public string STMM42 { get; set;}
    public string STMM43 { get; set;}
    public string STMM44 { get; set;}
    public string STMM45 { get; set;}
    public string STMM46 { get; set;}
    public string STMM47 { get; set;}
    public string STMM48 { get; set;}
    public string STMM49 { get; set;}
    public string STMM50 { get; set;}
    public string STMM63 { get; set;}
    public string STMM72 { get; set;}
    public string STMM76 { get; set;}
    public string STMM77 { get; set;}
}